#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "./../lib/smp_tool/cli"

# DEBUG:
# ARGV = "z -i exe/smp0.bin -c -5".split(" ")

begin
  Dry::CLI.new(SMPTool::CLI::Commands).call
  exit 0
rescue StandardError => e
  logger = SMPTool::CLI::Logger.new
  logger.error(e.message)
  exit 1
end
